variables:
  IMAGE_NAME: "co2appuk/app"
  IMAGE_TAG: "latest"

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY main@co2appuk.duckdns.org "       
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker ps -aqf 'ancestor=$IMAGE_NAME:$IMAGE_TAG' | xargs docker stop | xargs docker rm || true &&
        docker image rm $IMAGE_NAME:$IMAGE_TAG || true &&
        docker run -d -v /etc/letsencrypt/live/co2appuk.duckdns.org/privkey.pem:/app/privkey.pem -v /etc/letsencrypt/live/co2appuk.duckdns.org/fullchain.pem:/app/fullchain.pem --restart unless-stopped --network host $IMAGE_NAME:$IMAGE_TAG
      "
  only:
    - main
