version: "3"

services:
  co2app:
    image: co2appuk/app:latest
    container_name: co2app
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/live/co2appuk.duckdns.org/privkey.pem:/app/privkey.pem # set if you want to use https
      - /etc/letsencrypt/live/co2appuk.duckdns.org/fullchain.pem:/app/fullchain.pem # set if you want to use https
    network_mode: "host"
