version: "3"

services:
  co2app:
    image: co2appuk/app:latest
    container_name: co2app
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /my/own/datadir:/data/db
